Import('env')

sources = Split("""
    md5.c
    sha.c
    sha256.c
    aes.c
    hexdigest.c
""")


env.StaticLibrary(target = 'ucipher', source = sources)


if 'swig' in env['TOOLS']:
    import os
    SConscript(os.path.join('python', 'SConscript'))
    print "SWIG found, building Python bindings for mucipher."
else:
    print "WARNING: SWIG not found, NOT building Python bindings for mucipher."
#    SConscript(os.path.join('perl', 'SConscript')) 
#    can't use perl, cstring not implemented in swig-perl
