
Import('env')

files = Split("""
	__init__.py
	MucousTransfers.py
	MucousUserInfo.py
	MucousFormat.py
	MucousMuscan.py
	MucousPrivateChat.py
	MucousPopup.py 
	MucousHelp.py
	MucousLists.py
	MucousInput.py
	MucousNetworking.py
	MucousSearch.py
	MucousSetup.py
	MucousRoomsList.py
	MucousRecommendations.py
	MucousChatRooms.py
	MucousShares.py
	MucousAlerts.py
""")

import sys, os
py_ver = str(sys.version_info[0]) + "." + str(sys.version_info[1])
py_dest = env['DESTDIR'] + os.path.join(sys.prefix, "lib", "python" + py_ver, "site-packages", "pymucous")

install = env.Install(py_dest, files)
env.Alias('install_mucous', install)
env.Alias('install', 'install_mucous')
