def iface_build(target, source, env):
    from muscons import IfaceGen
    IfaceGen(str(target[0]), str(source[0]), str(source[1]))
    return 0

Import('env')
env.Command('messages.py', ['messages.py.in', '../../museekd/IfaceMessages.hh'], iface_build)

files = Split("""
	__init__.py
	driver.py
	messages.py
""")

import sys, os
py_ver = str(sys.version_info[0]) + "." + str(sys.version_info[1])
py_dest = env['DESTDIR'] + os.path.join(sys.prefix, "lib", "python" + py_ver, "site-packages", "museek")

install = env.Install(py_dest, files)
env.Alias('install_pymuseekd', install)
env.Alias('install', 'install_pymuseekd')
