.TH "MUSCAN" "1" "Release 0.2.0" "daelstorm" "Museek Daemon Plus"
.SH "NAME"
.LP 
\fBMuscan\fR \- File scanner for Museek
.SH "SYNOPSIS"
.B muscan
[\-c <\fIfilename\fP>] [\-\-config <\fIfilename\fP>]
[\-b] [\-\-buddy]
[\-v] [\-\-verbose]
[\-r] [\-\-rescan]
[\-n] [\-\-noscan]
[\-s <\fIdirectory\fP>] [\-\-share <\fIdirectory\fP>]
[\-u <\fIdirectory\fP>] [\-\-unshare <\fIdirectory\fP>]
[\-l] [\-\-list]
[\-h] [\-\-help]
.SH "DESCRIPTION"
.LP 
Muscan scans paths & files to be shared by \fImuseekd\fP(1). It creates a database of files, with meta\-data for MP3 and OGG Vorbis files, if Vorbis support was compiled in. There are two available shares databases, Normal and Buddies\-Only. Buddies\-Only is an optional shares database that, if enabled, is only accessible by the users you've chosen as "Buddies".
.LP 
Before running muscan, you will need a configured museekd,  which can be done with \fImusetup\fP(1) or fI>musetup\-gtk\fP(1), and add some shared paths with either of the setup tools or with \fImuscan\fP(1).
.SH "OPTIONS"
.LP 
Muscan accepts the following options:
.TP 
.B \-c <\fIfilename\fP>, \-\-config <\fIfilename\fP>
Use a different config file.
.TP 
.B \-b, \-\-buddy
Select Buddy\-Only Shares.
.TP 
.B \-s <\fIdirectory\fP>, \-\-share <\fIdirectory\fP> 
Add directory to shares.
.TP 
.B \-u <\fIdirectory\fP>, \-\-unshare <\fIdirectory\fP> 
Remove directory from shares.
.TP 
.B \-r, \-\-rescan
Rescan shares.
.TP 
.B \-n, \-\-noscan
Do not rescan shares.
.TP 
.B \-v, \-\-verbose
Be verbose while scanning shares.
.TP 
.B \-l, \-\-list
Display list of shared directories.
.TP 
.B \-h, \-\-help
Display Help, version and exit.
.SH "EXAMPLE"
.LP 
To run a quick shares update, run:
.LP 
\fBmuscan\fP or \fBmuscan \-b\fP
.LP 
To rescan everything, run:
.LP 
\fBmuscan \-r\fP or \fBmuscan \-b \-r\fP
.LP 
Alternatively you use a different config file with:
.LP 
\fBmuscan \-\-config config.xml\fP
.LP 

.SH "FILES"
.TP 
 \fI~/.museekd/config.xml\fR
The default location for the \fBmuseekd\fP config file.
.TP 
 \fI~/.museekd/config.shares\fR
The default location for the Normal shares database.
.TP 
 \fI~/.museekd/config.shares.state\fR
The default location for the active Normal shares database.
.TP 
 \fI~/.museekd/config.buddyshares\fR
The default location for the Buddy shares database.
.TP 
 \fI~/.museekd/config.buddyshares.state\fR
The default location for the active Buddy shares database's.
.SH "AUTHORS"
.LP 
Hyriand <hyriand@thegraveyard.org>
.LP 
daelstorm <daelstorm@gmail.com>
.SH "SEE ALSO"
.LP 
\fImucous\fP(1) \fImulog\fP(1) \fImurmur\fP(1) \fImuscand\fP(1) \fImuseekcontrol\fP(1) \fImuseekd\fP(1) \fImuseeq\fP(1) \fImusetup\fP(1) \fImusetup\-gtk\fP(1)
