.TH "MUSCAND" "1" "Release 0.2.0" "daelstorm" "Museek Daemon Plus"
.SH "NAME"
.LP 
\fBMuscand\fR \- File scanner daemon for Museek
.SH "SYNOPSIS"
.B muscand
[\-c <\fIfilename\fP>] [\-\-config <\fIfilename\fP>]
[\-b] [\-\-buddy]
[\-l] [\-\-list]
[\-h] [\-\-help]
[\-v] [\-\-verbose]
[\-\-no\-reload]
.SH "DESCRIPTION"
.LP 
Muscand is a FAM service that scans paths already configured by \fImuscan\fP(1) or \fImusetup\fP(1). If it detects changes to the paths, it will update the Shares Database it is watching after a few seconds. There are two available shares databases, Normal and Buddies\-Only. Buddies\-Only is an optional shares database that, if enabled, is only accessible by the users you've chosen as "Buddies".
.LP 
Before running muscand, you will need a configured museekd,  which can be done with \fImusetup\fP(1) or fI>musetup\-gtk\fP(1), and add some shared paths with either of the setup tools or with \fImuscan\fP(1).
.SH "OPTIONS"
.LP 
Muscand accepts the following options:
.TP 
.B \-c <\fIfilename\fP>, \-\-config <\fIfilename\fP>
Use a different config file.
.TP 
.B \-b, \-\-buddy
Select Buddy\-Only Shares.
.TP 
.B \-h, \-\-help
Display Help, version and exit.
.TP 
.B \-v, \-\-verbose
Be verbose while scanning shares.
.TP 
.B \-\-no\-reload
Don't ask museekd to reload the database
.SH "EXAMPLE"
.LP 
To run this program the standard way type:
.LP 
muscand
.LP 
Alternativly you use a different config file with:
.LP 
muscand \-\-config config.xml
.LP 
Or, you can watch Buddy\-Only shares:
.LP 
muscand \-\-buddy
.LP 
.SH "FILES"
.TP 
 \fI~/.museekd/config.xml\fR
The default location for the \fBmuseekd\fP config file.
.TP 
 \fI~/.museekd/config.shares\fR
The default location for the Normal shares database.
.TP 
 \fI~/.museekd/config.shares.state\fR
The default location for the active Normal shares database.
.TP 
 \fI~/.museekd/config.buddyshares\fR
The default location for the Buddy shares database.
.TP 
 \fI~/.museekd/config.buddyshares.state\fR
The default location for the active Buddy shares database's.
.SH "AUTHORS"
.LP 
Hyriand <hyriand@thegraveyard.org>
.LP 
daelstorm <daelstorm@gmail.com>
.SH "SEE ALSO"
.LP 
\fImucous\fP(1) \fImulog\fP(1) \fImurmur\fP(1) \fImuscan\fP(1) \fImuseekcontrol\fP(1) \fImuseekd\fP(1) \fImuseeq\fP(1) \fImusetup\fP(1) \fImusetup\-gtk\fP(1)
