# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chatroom.ui'
#
# Created: Fri Jul  3 17:50:21 2009
#      by: PyQt4 UI code generator 4.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Room(object):
    def setupUi(self, Room):
        Room.setObjectName("Room")
        Room.resize(559, 432)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Room)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter_2 = QtGui.QSplitter(Room)
        self.splitter_2.setLineWidth(1)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setHandleWidth(3)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtGui.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtGui.QSplitter(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setFrameShape(QtGui.QFrame.NoFrame)
        self.splitter.setLineWidth(1)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(6)
        self.splitter.setObjectName("splitter")
        self.StatusLog = QtGui.QTextEdit(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.StatusLog.sizePolicy().hasHeightForWidth())
        self.StatusLog.setSizePolicy(sizePolicy)
        self.StatusLog.setMaximumSize(QtCore.QSize(16777215, 200))
        self.StatusLog.setBaseSize(QtCore.QSize(0, 100))
        self.StatusLog.setFocusPolicy(QtCore.Qt.NoFocus)
        self.StatusLog.setReadOnly(True)
        self.StatusLog.setObjectName("StatusLog")
        self.ChatLog = QtGui.QTextEdit(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.ChatLog.sizePolicy().hasHeightForWidth())
        self.ChatLog.setSizePolicy(sizePolicy)
        self.ChatLog.setMinimumSize(QtCore.QSize(0, 0))
        self.ChatLog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ChatLog.setBaseSize(QtCore.QSize(0, 400))
        self.ChatLog.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ChatLog.setReadOnly(True)
        self.ChatLog.setObjectName("ChatLog")
        self.verticalLayout_2.addWidget(self.splitter)
        self.ChatEntry = QtGui.QLineEdit(self.layoutWidget)
        self.ChatEntry.setObjectName("ChatEntry")
        self.verticalLayout_2.addWidget(self.ChatEntry)
        self.widget = QtGui.QWidget(self.splitter_2)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.UserList = QtGui.QTreeWidget(self.widget)
        self.UserList.setAutoScrollMargin(16)
        self.UserList.setIndentation(0)
        self.UserList.setUniformRowHeights(True)
        self.UserList.setAllColumnsShowFocus(False)
        self.UserList.setColumnCount(4)
        self.UserList.setObjectName("UserList")
        self.UserList.headerItem().setText(0, "1")
        self.UserList.headerItem().setText(1, "2")
        self.UserList.headerItem().setText(2, "3")
        self.UserList.headerItem().setText(3, "4")
        self.verticalLayout.addWidget(self.UserList)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox = QtGui.QComboBox(self.widget)
        self.comboBox.setEnabled(True)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 1, 2, 1, 1)
        self.Close = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Close.sizePolicy().hasHeightForWidth())
        self.Close.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Close.setIcon(icon)
        self.Close.setObjectName("Close")
        self.gridLayout.addWidget(self.Close, 6, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.Log = QtGui.QCheckBox(self.widget)
        self.Log.setEnabled(True)
        self.Log.setObjectName("Log")
        self.gridLayout.addWidget(self.Log, 1, 1, 1, 1)
        self.Autojoin = QtGui.QCheckBox(self.widget)
        self.Autojoin.setEnabled(True)
        self.Autojoin.setObjectName("Autojoin")
        self.gridLayout.addWidget(self.Autojoin, 6, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 6, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_3.addWidget(self.splitter_2)

        self.retranslateUi(Room)
        QtCore.QMetaObject.connectSlotsByName(Room)

    def retranslateUi(self, Room):
        Room.setWindowTitle(QtGui.QApplication.translate("Room", "Room", None, QtGui.QApplication.UnicodeUTF8))
        self.UserList.setSortingEnabled(True)
        self.Close.setText(QtGui.QApplication.translate("Room", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.Log.setText(QtGui.QApplication.translate("Room", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.Autojoin.setText(QtGui.QApplication.translate("Room", "Autojoin", None, QtGui.QApplication.UnicodeUTF8))

