# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created: Fri Jul  3 17:50:21 2009
#      by: PyQt4 UI code generator 4.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_SettingsWindow(object):
    def setupUi(self, SettingsWindow):
        SettingsWindow.setObjectName("SettingsWindow")
        SettingsWindow.resize(550, 289)
        SettingsWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout_2 = QtGui.QVBoxLayout(SettingsWindow)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtGui.QSplitter(SettingsWindow)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.SettingsList = QtGui.QTreeWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SettingsList.sizePolicy().hasHeightForWidth())
        self.SettingsList.setSizePolicy(sizePolicy)
        self.SettingsList.setMinimumSize(QtCore.QSize(100, 0))
        self.SettingsList.setMaximumSize(QtCore.QSize(200, 16777215))
        self.SettingsList.setProperty("showDropIndicator", QtCore.QVariant(False))
        self.SettingsList.setAlternatingRowColors(True)
        self.SettingsList.setIconSize(QtCore.QSize(16, 16))
        self.SettingsList.setIndentation(20)
        self.SettingsList.setHeaderHidden(False)
        self.SettingsList.setColumnCount(1)
        self.SettingsList.setObjectName("SettingsList")
        self.SettingsList.headerItem().setText(0, "1")
        self.stackedWidget = QtGui.QStackedWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.PageLogin = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PageLogin.sizePolicy().hasHeightForWidth())
        self.PageLogin.setSizePolicy(sizePolicy)
        self.PageLogin.setObjectName("PageLogin")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.PageLogin)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtGui.QGroupBox(self.PageLogin)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setContentsMargins(0, 0, 9, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtGui.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_2.setMaxLength(30)
        self.lineEdit_2.setEchoMode(QtGui.QLineEdit.PasswordEchoOnEdit)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_2)
        self.checkBox = QtGui.QCheckBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setObjectName("checkBox")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.checkBox)
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_2.setObjectName("checkBox_2")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.checkBox_2)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_3)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.stackedWidget.addWidget(self.PageLogin)
        self.PageBlank = QtGui.QWidget()
        self.PageBlank.setObjectName("PageBlank")
        self.stackedWidget.addWidget(self.PageBlank)
        self.PageClients = QtGui.QWidget()
        self.PageClients.setObjectName("PageClients")
        self.groupBox_9 = QtGui.QGroupBox(self.PageClients)
        self.groupBox_9.setGeometry(QtCore.QRect(160, 90, 306, 215))
        self.groupBox_9.setObjectName("groupBox_9")
        self.stackedWidget.addWidget(self.PageClients)
        self.PageTransfers = QtGui.QWidget()
        self.PageTransfers.setObjectName("PageTransfers")
        self.groupBox_8 = QtGui.QGroupBox(self.PageTransfers)
        self.groupBox_8.setGeometry(QtCore.QRect(170, 100, 306, 215))
        self.groupBox_8.setObjectName("groupBox_8")
        self.stackedWidget.addWidget(self.PageTransfers)
        self.PageChatRooms = QtGui.QWidget()
        self.PageChatRooms.setObjectName("PageChatRooms")
        self.groupBox_7 = QtGui.QGroupBox(self.PageChatRooms)
        self.groupBox_7.setGeometry(QtCore.QRect(170, 20, 306, 215))
        self.groupBox_7.setObjectName("groupBox_7")
        self.stackedWidget.addWidget(self.PageChatRooms)
        self.PageUsers = QtGui.QWidget()
        self.PageUsers.setObjectName("PageUsers")
        self.groupBox_6 = QtGui.QGroupBox(self.PageUsers)
        self.groupBox_6.setGeometry(QtCore.QRect(180, 30, 306, 215))
        self.groupBox_6.setObjectName("groupBox_6")
        self.stackedWidget.addWidget(self.PageUsers)
        self.PageUserinfo = QtGui.QWidget()
        self.PageUserinfo.setObjectName("PageUserinfo")
        self.groupBox_5 = QtGui.QGroupBox(self.PageUserinfo)
        self.groupBox_5.setGeometry(QtCore.QRect(220, 50, 306, 215))
        self.groupBox_5.setObjectName("groupBox_5")
        self.stackedWidget.addWidget(self.PageUserinfo)
        self.PageShares = QtGui.QWidget()
        self.PageShares.setObjectName("PageShares")
        self.groupBox_4 = QtGui.QGroupBox(self.PageShares)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 30, 306, 215))
        self.groupBox_4.setObjectName("groupBox_4")
        self.stackedWidget.addWidget(self.PageShares)
        self.PageAppearance = QtGui.QWidget()
        self.PageAppearance.setObjectName("PageAppearance")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.PageAppearance)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtGui.QGroupBox(self.PageAppearance)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.stackedWidget.addWidget(self.PageAppearance)
        self.PageServer = QtGui.QWidget()
        self.PageServer.setObjectName("PageServer")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.PageServer)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_3 = QtGui.QGroupBox(self.PageServer)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.stackedWidget.addWidget(self.PageServer)
        self.verticalLayout.addWidget(self.splitter)
        self.buttonBox = QtGui.QDialogButtonBox(SettingsWindow)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(SettingsWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(SettingsWindow)

    def retranslateUi(self, SettingsWindow):
        SettingsWindow.setWindowTitle(QtGui.QApplication.translate("SettingsWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("SettingsWindow", "Connect to Museek Daemon", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SettingsWindow", "Museek Interface:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("SettingsWindow", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("SettingsWindow", "Load Tray icon at start", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("SettingsWindow", "CheckBox", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("SettingsWindow", "Config File:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("SettingsWindow", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("SettingsWindow", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("SettingsWindow", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("SettingsWindow", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("SettingsWindow", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("SettingsWindow", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("SettingsWindow", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("SettingsWindow", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))

