Import('env')

sources = Split("""
  Messages.cc
  MessageConnection.cc
  ServerConnection.cc
  BaseConnection.cc
  PeerManager.cc
  PeerConnection.cc
  PeerListener.cc
  DistribConnection.cc
  DistribManager.cc
  Museek.cc
  ShareBase.cc
  TransferManager.cc
  TransferConnection.cc
  Recoder.cc
""")

pch = Split("""
  mu.hh
""")

# Check for zlib
conf = env.Configure()

if not conf.CheckLibWithHeader('z', 'zlib.h', 'C++', 'inflate(0, Z_FINISH);'):
    print 'Please install ZLIB and point scons at it. If problem persists, erase the system.h file, and try again.'
    Exit(1)

conf.Finish()

env.StaticLibrary(target = 'museek', source = sources)
