.TH "MUSEEQ" "1" "Release 0.1.9" "daelstorm" "Museek Daemon Plus"
.SH "NAME"
.LP 
\fBMuseeq\fR \- QT GUI for the Museek Daemon
.SH "SYNOPSIS"
.B museeq
No options

.SH "DESCRIPTION"
.LP 
Museeq is a QT GUI for the Museek Daemon. It provides a standard set of Soulseek / Soulfind features, including Chat Rooms; Private Chat; Transferring files; Searching; Buddies, Banned, Ignored and Trusted users lists; Interests & Recommendations; User info; and Browsing of users' Shared files.
.LP 
Before running museeq, you will need a \fImuseekd\fP(1) running, and configured with \fImusetup\fP(1).
.SH "EXAMPLE"
.LP 
To run this program the standard way type:
.LP 
museeq

.SH "FILES"
.TP 
 \fI~/.qt/thegraveyard.orgrc\fR
The \fBmuseeq\fP config file.
.SH "AUTHORS"
.LP 
Hyriand <hyriand@thegraveyard.org>
.LP 
daelstorm <daelstorm@gmail.com>
.SH "SEE ALSO"
.LP 
\fImuseekd\fP(1) \fImuscan\fP(1) \fImuscand\fP(1) \fImuseekcontrol\fP(1) \fImucous\fP(1) \fImulog\fP(1) \fImusetup\fP(1)
