/* Auto-generated by build script, do not edit */

#define MULOG_DEBUG 1

#define SIZE_INT 4
#define SIZE_SHORT 2
#define SIZE_LONGINT 4

#define HAVE_STDIO_H 1
#include <stdio.h>

#define HAVE_SYS_TYPES_H 1
#include <sys/types.h>

#define HAVE_SYS_STAT_H 1
#include <sys/stat.h>

#define HAVE_STDLIB_H 1
#include <stdlib.h>

#define HAVE_STDDEF_H 1
#include <stddef.h>

#define HAVE_MEMORY_H 1
#include <memory.h>

#define HAVE_STRING_H 1
#include <string.h>

#define HAVE_STRINGS_H 1
#include <strings.h>

#define HAVE_INTTYPES_H 1
#include <inttypes.h>

#define HAVE_STDBOOL_H 1
#include <stdbool.h>

#define HAVE_STDINT_H 1
#include <stdint.h>

#define HAVE_UNISTD_H 1
#include <unistd.h>

#define HAVE_STDARG_H 1
#include <stdarg.h>

#define HAVE_NETDB_H 1
#include <netdb.h>

#define HAVE_SYS_SOCKET_H 1
#include <sys/socket.h>

#define HAVE_SYS_UN_H 1
#include <sys/un.h>

#define HAVE_FCNTL_H 1
#include <fcntl.h>

#define HAVE_NETINET_IN_H 1
#include <netinet/in.h>

#define HAVE_SYS_POLL_H 1
#include <sys/poll.h>

#define HAVE_PWD_H 1
#include <pwd.h>

#define HAVE_ERRNO_H 1
#include <errno.h>

#define ICONV_IN char **

#define HAVE_EPOLL_CTL 1
#include <sys/epoll.h>

#define HAVE_SIGNAL_H 1
#include <signal.h>
#define RETSIGTYPE void

#define UNIX_PATH_MAX 108

#include <sys/time.h>
#include <time.h>

#include <dirent.h>
#define NAMELEN(dirent) strlen((dirent)->d_name
#define HAVE_SCANDIR 1
#define SCANDIR_ENTRY dirent

#define _FILE_OFFSET_BITS 64

typedef unsigned int uint32;


