Import('env')
import os

def build_setup(target, source, env):
    open(str(target[0]), 'w').write( open(str(source[0]), 'r').read() )
    os.chmod(str(target[0]), 0755)
    return 0

try:
	import pyexpat
	print "Dependency of musetup found: pyexpat"
except:
	print "\nWARNING: Dependency of musetup NOT found: pyexpat missing!"

targets = [env.Command('musetup', ['musetup.in'], build_setup)]
manfile = ["musetup.1"]
if 'swig' in env['TOOLS']:
	targets.append('mulog')
	targets.append('museekcontrol')
	manfile.append("mulog.1")
 	manfile.append("museekcontrol.1")


man_install = env.Install(env['DESTDIR'] + env['MANDIR'], manfile)

install = env.Install(env['DESTDIR'] + env['BINDIR'], targets)
env.Alias('install_pymuseekd', man_install)
env.Alias('install_pymuseekd', install)
env.Alias('install', 'install_pymuseekd')

if 'swig' in env['TOOLS']:
	SConscript(os.path.join('museek', 'SConscript'))
