Import('env')
import os

def build_setup(target, source, env):
    open(str(target[0]), 'w').write( open(str(source[0]), 'r').read() )
    os.chmod(str(target[0]), 0755)
    return 0

targets = [env.Command('musetup', ['musetup.in'], build_setup)]
if 'swig' in env['TOOLS']:
	targets.append('mulog', 'museekcontrol')

manfile = ["musetup.1", "mulog.1"]
man_install = env.Install(env['DESTDIR'] + env['MANDIR'], manfile)

install = env.Install(env['DESTDIR'] + env['BINDIR'], targets)
env.Alias('install_pymuseekd', man_install)
env.Alias('install_pymuseekd', install)
env.Alias('install', 'install_pymuseekd')

if 'swig' in env['TOOLS']:
	SConscript(os.path.join('museek', 'SConscript'))
