Import('env')
import os

try:
	import pyexpat
	print "pyexpat found, musetup will run properly."
except:
	print "\nWARNING: pyexpat not found, musetup will NOT run, but will be installed."

targets = ["musetup"]
manfile = ["musetup.1"]
print "* musetup will be installed"
if env["MUSETUPGTK"]:
	try:
		import gtk
		print "PyGTK found, musetup-gtk will run properly."
	except:
		try:
			import pygtk
			print "PyGTK found, musetup-gtk will run properly."
		except:
			print "\nWARNING: PyGTK not found, musetup-gtk will NOT run, but will be installed."
	
	targets.append('musetup-gtk')
	manfile.append ("musetup-gtk.1")
	print "* musetup-gtk will be installed"

targets.append('mulog')
targets.append('museekcontrol')
manfile.append("mulog.1")
manfile.append("museekcontrol.1")
print "* mulog will be installed"
print "* museekcontrol will be installed"

man_install = env.Install(env['DESTDIR'] + env['MANDIR'], manfile)

install = env.Install(env['DESTDIR'] + env['BINDIR'], targets)
env.Alias('install_pymuseekd', man_install)
env.Alias('install_pymuseekd', install)
env.Alias('install', 'install_pymuseekd')

if env['PYMUCIPHER'] and 'swig' in env['TOOLS']:
	pass
else:
	print "WARNING: PyMucipher is not going to be installed, so you should install either PyCrypto, or PyMucipher"
SConscript(os.path.join('museek', 'SConscript'))
print
