Import("env")

sources = Split("""
    ClientConnection.cc
    ListenConnection.cc
    ConnectionManager.cc
    TrafficTracker.cc
""")


conf = env.Configure()

# Check if we need libsocket and/or libnsl

conf.CheckLib('socket', 'setsockopt')
conf.CheckLib('nsl', 'gethostent')

conf.Finish()


env.StaticLibrary(target = 'museekal', source = sources)
print