Import('env')
import os

try:
	import pyexpat
	print "pyexpat found, musetup will run properly."
except:
	print "\nWARNING: pyexpat not found, musetup will NOT run, but will be installed."

targets = ["musetup"]
manfile = ["musetup.1"]
print "* musetup will be installed"
if env["MUSETUPGTK"]:
	try:
		import gtk
		print "PyGTK found, musetup-gtk will run properly."
	except:
		try:
			import pygtk
			print "PyGTK found, musetup-gtk will run properly."
		except:
			print "\nWARNING: PyGTK not found, musetup-gtk will NOT run, but will be installed."
	
	targets.append('musetup-gtk')
	manfile.append ("musetup-gtk.1")
	print "* musetup-gtk will be installed"

man_install = env.Install(env['DESTDIR'] + env['MANDIR'], manfile)
install = env.Install(env['DESTDIR'] + env['BINDIR'], targets)

env.Alias('install_setup', man_install)
env.Alias('install_setup', install)
env.Alias('install', 'install_setup')

print
